/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7SNMkB8UMukVgcWJYokeAQ
// Component: UzzuDE7ANnFL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ApiRequest } from "@/fragment/components/api-request"; // plasmic-import: a17-BE4K1UE7/codeComponent
import Select from "../../Select"; // plasmic-import: GgjLI5qwOqwu/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7SNMkB8UMukVgcWJYokeAQ/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 7SNMkB8UMukVgcWJYokeAQ/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 7SNMkB8UMukVgcWJYokeAQ/projectcss
import sty from "./PlasmicPublicCalendar3.module.css"; // plasmic-import: UzzuDE7ANnFL/css

createPlasmicElementProxy;

export type PlasmicPublicCalendar3__VariantMembers = {};
export type PlasmicPublicCalendar3__VariantsArgs = {};
type VariantPropType = keyof PlasmicPublicCalendar3__VariantsArgs;
export const PlasmicPublicCalendar3__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPublicCalendar3__ArgsType = {};
type ArgPropType = keyof PlasmicPublicCalendar3__ArgsType;
export const PlasmicPublicCalendar3__ArgProps = new Array<ArgPropType>();

export type PlasmicPublicCalendar3__OverridesType = {
  root?: Flex__<"div">;
  apiRequest?: Flex__<typeof ApiRequest>;
  selectProperty?: Flex__<typeof Select>;
  apiRequest2?: Flex__<typeof ApiRequest>;
  embedHtml?: Flex__<typeof Embed>;
  img?: Flex__<typeof PlasmicImg__>;
  fetchImage?: Flex__<typeof ApiRequest>;
};

export interface DefaultPublicCalendar3Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPublicCalendar3__RenderFunc(props: {
  variants: PlasmicPublicCalendar3__VariantsArgs;
  args: PlasmicPublicCalendar3__ArgsType;
  overrides: PlasmicPublicCalendar3__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selectProperty.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.apiRequest.data[0].name;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "apiRequest.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest2.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest2"
      },
      {
        path: "apiRequest2.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest2"
      },
      {
        path: "apiRequest2.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest2"
      },
      {
        path: "fetchImage.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "fetchImage"
      },
      {
        path: "fetchImage.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "fetchImage"
      },
      {
        path: "fetchImage.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "fetchImage"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicPublicCalendar3.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicPublicCalendar3.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicPublicCalendar3.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__btX8W)}>
            <ApiRequest
              data-plasmic-name={"apiRequest"}
              data-plasmic-override={overrides.apiRequest}
              className={classNames("__wab_instance", sty.apiRequest)}
              errorDisplay={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aEAf
                  )}
                >
                  {"Error fetching data"}
                </div>
              }
              loadingDisplay={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5FCju
                  )}
                >
                  {"Loading..."}
                </div>
              }
              method={"GET"}
              onError={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "apiRequest",
                  "error"
                ]).apply(null, eventArgs);
              }}
              onLoading={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "apiRequest",
                  "loading"
                ]).apply(null, eventArgs);
              }}
              onSuccess={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["apiRequest", "data"]).apply(
                  null,
                  eventArgs
                );
              }}
              ref={ref => {
                $refs["apiRequest"] = ref;
              }}
              url={
                "https://gateway.rentamon.com/webhook/public_calendar_get_property_id"
              }
            >
              <div className={classNames(projectcss.all, sty.freeBox__y47CQ)}>
                <Select
                  data-plasmic-name={"selectProperty"}
                  data-plasmic-override={overrides.selectProperty}
                  className={classNames("__wab_instance", sty.selectProperty)}
                  onChange={async (...eventArgs: any) => {
                    ((...eventArgs) => {
                      generateStateOnChangeProp($state, [
                        "selectProperty",
                        "value"
                      ])(eventArgs[0]);
                    }).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  options={(() => {
                    try {
                      return $state.apiRequest.data.map(item => item.name);
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()}
                  placeholder={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tvaq6
                      )}
                    >
                      {"\u0627\u0642\u0627\u0645\u062a\u06af\u0627\u0647.."}
                    </div>
                  }
                  value={generateStateValueProp($state, [
                    "selectProperty",
                    "value"
                  ])}
                />
              </div>
              <ApiRequest
                data-plasmic-name={"apiRequest2"}
                data-plasmic-override={overrides.apiRequest2}
                className={classNames("__wab_instance", sty.apiRequest2)}
                errorDisplay={null}
                loadingDisplay={null}
                method={"GET"}
                onError={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "apiRequest2",
                    "error"
                  ]).apply(null, eventArgs);
                }}
                onLoading={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "apiRequest2",
                    "loading"
                  ]).apply(null, eventArgs);
                }}
                onSuccess={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "apiRequest2",
                    "data"
                  ]).apply(null, eventArgs);
                }}
                ref={ref => {
                  $refs["apiRequest2"] = ref;
                }}
                url={(() => {
                  try {
                    return (() => {
                      const isMiaan =
                        window.location.hostname.includes("miaan.ir");
                      const gatewayBase = isMiaan
                        ? "https://gateway.miaan.ir"
                        : "https://gateway.rentamon.com";
                      return `${gatewayBase}/webhook/public_calendar_api?property_id=${$state.apiRequest.data.find(property => property.name === $state.selectProperty.value).id}`;
                    })();
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              >
                <div className={classNames(projectcss.all, sty.freeBox__cdJmA)}>
                  <Embed
                    data-plasmic-name={"embedHtml"}
                    data-plasmic-override={overrides.embedHtml}
                    className={classNames("__wab_instance", sty.embedHtml)}
                    code={(() => {
                      try {
                        return `<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
<meta charset="UTF-8">
<script src="https://cdn.jsdelivr.net/npm/jalaali-js/dist/jalaali.js"></script>

<style>
  #custom-calendar-container {
    --bg-booked: #9e9e9e;
    --bg-free: #ffffff;
    --border-free: #ccc;
    --text-booked: #fff;
    --text-free: #333;
    --text-friday: #ff3b30;
    --bg-selected: #333;
    --radius: 10px;
    
    width: 100%;
    max-width: 400px;
    padding: 10px;
    box-sizing: border-box;
    direction: rtl;
  }

  #custom-calendar-container * {
    box-sizing: border-box;
  }

  #custom-calendar-container .header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 25px;
    font-size: 1.2rem;
    font-weight: bold;
    color: #333;
  }

  #custom-calendar-container .nav-btn {
    background: transparent !important;
    border: none !important;
    box-shadow: none !important;
    cursor: pointer;
    padding: 5px 15px;
    font-size: 1.5rem !important;
    color: #888 !important;
    transition: color 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
    line-height: 1;
  }

  #custom-calendar-container .nav-btn:disabled {
    color: #e0e0e0 !important;
    cursor: not-allowed;
  }

  #custom-calendar-container .weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    text-align: center;
    margin-bottom: 15px;
    font-size: 0.9rem;
    color: #666;
    font-weight: normal;
  }

  #custom-calendar-container .days-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 8px;
  }

  #custom-calendar-container .day-cell {
    aspect-ratio: 1/1.2;
    border-radius: var(--radius);
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1.1rem;
    cursor: pointer;
    position: relative;
    transition: all 0.2s;
    padding: 0;
    margin: 0;
  }

  #custom-calendar-container .free {
    background-color: var(--bg-free);
    border: 1px solid var(--border-free);
    color: var(--text-free);
  }

  #custom-calendar-container .booked {
    background-color: var(--bg-booked);
    border: 1px solid var(--bg-booked);
    color: var(--text-booked);
    cursor: default;
  }

  #custom-calendar-container .selected {
    background-color: var(--bg-selected) !important;
    border-color: var(--bg-selected) !important;
    color: #fff !important;
  }

  #custom-calendar-container .free.friday {
    color: var(--text-friday);
  }

  #custom-calendar-container .past-day {
    opacity: 0;
    pointer-events: none;
  }
  
  #custom-calendar-container .empty-slot {
    pointer-events: none;
  }

  #custom-calendar-container .loading {
    text-align: center;
    padding: 20px;
    color: #666;
    font-size: 0.9rem;
    font-family: inherit;
  }

  #custom-calendar-container .legend {
    display: flex;
    justify-content: flex-start;
    align-items: center;
    margin-top: 20px;
    gap: 15px;
    font-size: 0.8rem;
    color: #666;
  }

  #custom-calendar-container .legend-item {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  #custom-calendar-container .legend-box {
    width: 16px;
    height: 16px;
    border-radius: 4px;
  }
  
  #custom-calendar-container .box-free {
    background: #fff;
    border: 1px solid #ccc;
  }
  
  #custom-calendar-container .box-booked {
    background: var(--bg-booked);
  }

</style>
</head>
<body>

<div id="custom-calendar-container">
  
  <div class="header">
    <button class="nav-btn" id="prev-btn">&#10094;</button> 
    <span id="month-year-label">...</span>
    <button class="nav-btn" id="next-btn">&#10095;</button>
  </div>

  <div class="weekdays">
    <div>ش</div>
    <div>ی</div>
    <div>د</div>
    <div>س</div>
    <div>چ</div>
    <div>پ</div>
    <div>ج</div>
  </div>

  <div id="loading-msg" class="loading">در حال بارگذاری تقویم...</div>
  <div class="days-grid" id="calendar-grid"></div>

  <div class="legend" id="legend-section" style="display:none;">
    <div class="legend-item">
      <div class="legend-box box-free"></div>
      <span>خالی</span>
    </div>
    <div class="legend-item">
      <div class="legend-box box-booked"></div>
      <span>پر</span>
    </div>
  </div>

</div>

<script>
{ 
  // *** شروع بلاک اسکوپ ***
  // این آکولاد باز باعث می‌شود متغیرها فقط در همین اجرا معتبر باشند و با اجرای بعدی تداخل نکنند.

  const PRELOADED_DATES = ${JSON.stringify($state.apiRequest2.data.dates || [])};
  const MAX_MONTHS_AHEAD = 3;

  let bookedDates = new Set();
  let selectedDate = null;
  
  const today = new Date();
  const todayJ = jalaali.toJalaali(today);
  
  let currentYear = todayJ.jy;
  let currentMonth = todayJ.jm;
  const startYear = todayJ.jy;
  const startMonth = todayJ.jm;

  const monthNames = ["", "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند"];

  function toPersianNum(num) {
      const farsiDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
      return num.toString().replace(/\\d/g, x => farsiDigits[x]);
  }

  function initCalendar() {
    try {
      if (PRELOADED_DATES && Array.isArray(PRELOADED_DATES)) {
        bookedDates = new Set(PRELOADED_DATES);
      }
      
      const loadMsg = document.getElementById('loading-msg');
      if(loadMsg) loadMsg.style.display = 'none';
      
      const legSec = document.getElementById('legend-section');
      if(legSec) legSec.style.display = 'flex';
      
      renderCalendar();
      updateNavButtons();
      
    } catch (error) {
      console.error("Error initializing calendar:", error);
      const loadMsg = document.getElementById('loading-msg');
      if(loadMsg) loadMsg.innerText = "خطا در بارگذاری";
    }
  }

  function renderCalendar() {
    const grid = document.getElementById('calendar-grid');
    const label = document.getElementById('month-year-label');
    
    if (!grid || !label) return; // اطمینان از وجود المنت‌ها

    grid.innerHTML = '';
    label.innerText = monthNames[currentMonth] + " " + toPersianNum(currentYear);

    const daysInMonth = jalaali.jalaaliMonthLength(currentYear, currentMonth);
    
    const gDate = jalaali.toGregorian(currentYear, currentMonth, 1);
    const dateObj = new Date(gDate.gy, gDate.gm - 1, gDate.gd);
    let startDayOfWeek = dateObj.getDay(); 
    
    const jsDayToJalaliDay = [1, 2, 3, 4, 5, 6, 0];
    let startDayIndex = jsDayToJalaliDay[startDayOfWeek];

    for (let i = 0; i < startDayIndex; i++) {
      const emptyCell = document.createElement('div');
      emptyCell.className = 'empty-slot';
      grid.appendChild(emptyCell);
    }

    for (let day = 1; day <= daysInMonth; day++) {
      const cell = document.createElement('div');
      
      const mStr = currentMonth < 10 ? '0' + currentMonth : currentMonth;
      const dStr = day < 10 ? '0' + day : day;
      const dateString = currentYear + "-" + mStr + "-" + dStr;
      
      const isBooked = bookedDates.has(dateString);
      const isPast = isDateInPast(currentYear, currentMonth, day);
      
      const dayOfWeekIndex = (day - 1 + startDayIndex) % 7;
      const isFriday = (dayOfWeekIndex === 6);

      let classes = 'day-cell';
      if (isPast) {
        classes += ' past-day';
      } else if (isBooked) {
        classes += ' booked';
      } else {
        classes += ' free';
        if (isFriday) classes += ' friday';
        if (selectedDate === dateString) classes += ' selected';
      }

      cell.className = classes;
      cell.innerText = toPersianNum(day);

      if (!isBooked && !isPast) {
        cell.onclick = function() { selectDate(dateString, cell); };
      }

      grid.appendChild(cell);
    }
  }

  function isDateInPast(y, m, d) {
    if (y < todayJ.jy) return true;
    if (y > todayJ.jy) return false;
    if (m < todayJ.jm) return true;
    if (m > todayJ.jm) return false;
    return d < todayJ.jd;
  }

  function selectDate(dateStr, cell) {
    var allSelected = document.querySelectorAll('#custom-calendar-container .selected');
    for(var i=0; i<allSelected.length; i++) {
        allSelected[i].classList.remove('selected');
    }
    
    selectedDate = dateStr;
    cell.classList.add('selected');
    console.log("Selected:", dateStr);
  }

  function changeMonth(offset) {
    let nextM = currentMonth + offset;
    let nextY = currentYear;

    if (nextM > 12) { nextM = 1; nextY++; }
    else if (nextM < 1) { nextM = 12; nextY--; }

    currentMonth = nextM;
    currentYear = nextY;
    
    renderCalendar();
    updateNavButtons();
  }

  function updateNavButtons() {
    const prevBtn = document.getElementById('prev-btn');
    const nextBtn = document.getElementById('next-btn');
    
    if(!prevBtn || !nextBtn) return;

    // حذف ایونت‌های قبلی با کلون کردن دکمه (چون در محیط ری‌رندر ممکن است ایونت‌ها دوبل شوند)
    // ساده‌ترین راه در اینجا بازتعریف onclick است که در پایین انجام شده است

    prevBtn.onclick = function() { changeMonth(-1); };
    nextBtn.onclick = function() { changeMonth(1); };

    if (currentYear === startYear && currentMonth === startMonth) {
      prevBtn.disabled = true;
    } else {
      prevBtn.disabled = false;
    }

    let diffMonths = (currentYear - startYear) * 12 + (currentMonth - startMonth);
    if (diffMonths >= MAX_MONTHS_AHEAD) {
      nextBtn.disabled = true;
    } else {
      nextBtn.disabled = false;
    }
  }

  // اجرا
  setTimeout(initCalendar, 50);

} // *** پایان بلاک اسکوپ ***
</script>
</body>
</html>`;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "";
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
              </ApiRequest>
            </ApiRequest>
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={(() => {
                try {
                  return $state.fetchImage.data.property_pic_link;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              width={
                hasVariant(globalVariants, "screen", "mobile") ? `` : "400"
              }
            />

            <ApiRequest
              data-plasmic-name={"fetchImage"}
              data-plasmic-override={overrides.fetchImage}
              children={null}
              className={classNames("__wab_instance", sty.fetchImage)}
              errorDisplay={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ixXja
                  )}
                >
                  {"Error fetching data"}
                </div>
              }
              loadingDisplay={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__orq2E
                  )}
                >
                  {"Loading..."}
                </div>
              }
              method={"GET"}
              onError={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "fetchImage",
                  "error"
                ]).apply(null, eventArgs);
              }}
              onLoading={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "fetchImage",
                  "loading"
                ]).apply(null, eventArgs);
              }}
              onSuccess={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, ["fetchImage", "data"]).apply(
                  null,
                  eventArgs
                );
              }}
              params={undefined}
              ref={ref => {
                $refs["fetchImage"] = ref;
              }}
              url={(() => {
                try {
                  return (() => {
                    const isMiaan =
                      window.location.hostname.includes("miaan.ir");
                    const gatewayBase = isMiaan
                      ? "https://gateway.miaan.ir"
                      : "https://gateway.rentamon.com";
                    return `${gatewayBase}/webhook/property_image_url?property_id=${$state.apiRequest.data.find(property => property.name === $state.selectProperty.value).id}`;
                  })();
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            />
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___1EmGf)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__deWAl
              )}
            >
              {"Enter some text"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "apiRequest",
    "selectProperty",
    "apiRequest2",
    "embedHtml",
    "img",
    "fetchImage"
  ],
  apiRequest: ["apiRequest", "selectProperty", "apiRequest2", "embedHtml"],
  selectProperty: ["selectProperty"],
  apiRequest2: ["apiRequest2", "embedHtml"],
  embedHtml: ["embedHtml"],
  img: ["img"],
  fetchImage: ["fetchImage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  apiRequest: typeof ApiRequest;
  selectProperty: typeof Select;
  apiRequest2: typeof ApiRequest;
  embedHtml: typeof Embed;
  img: typeof PlasmicImg__;
  fetchImage: typeof ApiRequest;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPublicCalendar3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPublicCalendar3__VariantsArgs;
    args?: PlasmicPublicCalendar3__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPublicCalendar3__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPublicCalendar3__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPublicCalendar3__ArgProps,
          internalVariantPropNames: PlasmicPublicCalendar3__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPublicCalendar3__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPublicCalendar3";
  } else {
    func.displayName = `PlasmicPublicCalendar3.${nodeName}`;
  }
  return func;
}

export const PlasmicPublicCalendar3 = Object.assign(
  // Top-level PlasmicPublicCalendar3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    apiRequest: makeNodeComponent("apiRequest"),
    selectProperty: makeNodeComponent("selectProperty"),
    apiRequest2: makeNodeComponent("apiRequest2"),
    embedHtml: makeNodeComponent("embedHtml"),
    img: makeNodeComponent("img"),
    fetchImage: makeNodeComponent("fetchImage"),

    // Metadata about props expected for PlasmicPublicCalendar3
    internalVariantProps: PlasmicPublicCalendar3__VariantProps,
    internalArgProps: PlasmicPublicCalendar3__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "تقویم اقامتگاه",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPublicCalendar3;
/* prettier-ignore-end */
