// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicNavigationRntFooter,
  DefaultNavigationRntFooterProps
} from "./plasmic/website_starter/PlasmicNavigationRntFooter";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface NavigationRntFooterProps extends Omit<DefaultNavigationRntFooterProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultNavigationRntFooterProps altogether and have
// total control over the props for your component.
export interface NavigationRntFooterProps
  extends DefaultNavigationRntFooterProps {}

function NavigationRntFooter_(
  props: NavigationRntFooterProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicNavigationRntFooter to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicNavigationRntFooter are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all NavigationRntFooterProps here, but feel free
  // to do whatever works for you.

  return <PlasmicNavigationRntFooter navFoot={{ ref }} {...props} />;
}

const NavigationRntFooter = React.forwardRef(NavigationRntFooter_);
export default NavigationRntFooter;
