// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/website_starter/PlasmicGlobalContextsProvider";

import { Plasmicمدیریتاقامتگاه } from "../../components/plasmic/website_starter/Plasmic\u0645\u062F\u06CC\u0631\u06CC\u062A\u0627\u0642\u0627\u0645\u062A\u06AF\u0627\u0647";
import { useRouter } from "next/router";

function مدیریتاقامتگاه() {
  // Use Plasmicمدیریتاقامتگاه to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmicمدیریتاقامتگاه are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, Plasmicمدیریتاقامتگاه is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <Plasmicمدیریتاقامتگاه />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default مدیریتاقامتگاه;
