# ===================================
#  TEST TO PROVE THE FILE IS UPDATING
# ===================================

name: 🧪 My Test Workflow - Version 3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: A simple test step
        run: echo "Hello world! If you see this, the file was updated correctly."
