name: Mirror to HamGit via Proxy

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Proxy
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          if [ -n "$PROXY_URL" ]; then
            echo "Configuring git to use the proxy..."
            git config --global https.proxy "$PROXY_URL"
          else
            echo "No proxy URL provided, skipping proxy config."
          fi

      - name: Push to HamGit Mirror
        env:
          HAMGIT_PAT: ${{ secrets.HAMGIT_PAT }}
        run: |
          echo "Pushing changes to HamGit..."
          git remote set-url --push origin "https://rentamon.co:${HAMGIT_PAT}@hamgit.ir/rentamon.co/rentamon-plasmic.git"
          git push --force origin main

      - name: Cleanup Git Proxy
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
        if: always()
        run: |
          if [ -n "$PROXY_URL" ]; then
            echo "Cleaning up proxy configuration..."
            git config --global --unset https.proxy
          fi
